### ISSUE TITLE
Some ads imports not working

### ISSUE THREAD

**Issue by borkur** [oracle-samples/oci-data-science-ai-samples#270]
Hello, in the labs/employee-attrition/notebooks/employee-attrition.ipynb we import e.g. these
```
from ads.explanations.explainer import ADSExplainer
from ads.explanations.mlx_whatif_explainer import MLXWhatIfExplainer
from ads.explanations.mlx_global_explainer import MLXGlobalExplainer
from ads.explanations.mlx_local_explainer import MLXLocalExplainer
```
but they all fail, with errors like:
```
ModuleNotFoundError: No module named 'mlx'
```
more detailed:
```ERROR - Exception
Traceback (most recent call last):
  File "/home/datascience/conda/rm_training_condav1/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1552/4198881629.py", line 23, in <module>
    from ads.explanations.explainer import ADSExplainer
  File "/home/datascience/conda/rm_training_condav1/lib/python3.8/site-packages/ads/explanations/__init__.py", line 9, in <module>
    import mlx
ModuleNotFoundError: No module named 'mlx'
ModuleNotFoundError: No module named 'mlx'
```
and then
```
$ pip install mlx
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
```

I don't quite understand how this notebook can work?

**Comment by borkur** [comment]
Also:
```
>>> import ads
>>> ads.hello()


  O  o-o   o-o
 / \ |  \ |
o---o|   O o-o
|   ||  /     |
o   oo-o  o--o

ADS SDK version: 2.8.0
Pandas version: 1.5.3
Debug mode: False
```

**Comment by z7ye** [comment]
Hi Borkur, we are deprecaing this module. This is to in favor of working directly with AutoMLx library. The AutoMlx library can be found in `automlx_p38_cpu_v#` conda pack. The latest documentation can be found at https://docs.oracle.com/en-us/iaas/tools/automlx/latest/html/multiversion/v23.1.1/index.html. Notebook examples can be found at https://github.com/oracle-samples/automlx .
