### ISSUE TITLE
ModuleNotFoundError: No module named 'ads.dataflow'

### ISSUE THREAD

**Issue by sauravmishra1710** [oracle-samples/oci-data-science-ai-samples#336]
When trying to understand and execute the employee attrition notebook locally, I get the following import error - 

```
ERROR - Exception
Traceback (most recent call last):
  File "/Users/XXXXXX/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-28ffd096b9e1>", line 20, in <cell line: 20>
    from ads.dataflow.dataflow import DataFlow
ModuleNotFoundError: No module named 'ads.dataflow'
ModuleNotFoundError: No module named 'ads.dataflow'
```

I see in the release notes that the [`ads.dataflow` package has been deprecated since 2.8.6 release](https://accelerated-data-science.readthedocs.io/en/latest/release_notes.html#id3). However, the notebook has not been updated. 

Is there a new version of the notebook? OR Howis this being handled now?

**Comment by sauravmishra1710** [comment]
any updates on this?
